creation_rules:
  - key_groups:
      - pgp: 
          - C9230708DD20DB6A887C9B80577E858EDCFECA83
        age:
          - age1y3xfg0mcaadnxj0el7ectxz90dey4ymtqreup3kdpx55hy2esv6qq2xvd3 # nixos101
          - age1lfgj9pjfuf55p45tu74r2hmrvgzphc0ygavxz0067xcju0untf9qtrxze9 # nixos102
